# Generated by Django 5.0.7 on 2026-05-08 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0005_alter_review_options_review_rating_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="audio",
        ),
        migrations.RemoveField(
            model_name="story",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="story",
            name="video",
        ),
        migrations.CreateModel(
            name="StoryMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("photo", "Фото"),
                            ("video", "Видео"),
                            ("audio", "Аудио"),
                        ],
                        max_length=10,
                        verbose_name="Тип файла",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="stories/media/", verbose_name="Файл"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружено"),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="stories.story",
                        verbose_name="История",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл истории",
                "verbose_name_plural": "Файлы истории",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
